spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: app_user
    password: app_password
    hikari:
      pool-name: UrlShortenerHikariPool
      minimum-idle: 2
      maximum-pool-size: 10
      idle-timeout: 300000
      max-lifetime: 1800000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show-sql: false
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    enabled: true

aws:
  dynamodb:
    endpoint: http://localhost:4566
    region: us-east-1
    access-key: test
    secret-key: test
    table-name: url
  cloud:
    credentials:
      use-default-aws-credentials-chain: false

app:
  base-url: "http://localhost:8080"
  hashids:
    salt: "6tqpVWWvusxiDnK0iHXD5xsNBTSkN/BV7ojsWkjBu10="
    min-length: 7
  id-generator:
    block-size: 1000
  security:
    jwt:
      secret: "X43Q+VZwzlK3qYRVPzn3fnvNJvvWJmOG+yV0r+tj9ok="
      issuer: ${spring.application.name}
      access-token-expiration-minutes: 15
      refresh-token-expiration-days: 7