spring:
  application:
    name: url-shortener
  profiles:
    active: dev
  mvc:
    problemdetails:
      enabled: true

app:
  idempotency:
    protected-uris:
      - /api/v1/auth/register
      - /api/v1/auth/verify-email
